pub mod capnp_rpc {

    // this mod contains file generated by capnp or other build tools.
    // we shouldn't manually change it. Thus skip format and lint check.
    #[rustfmt::skip]
    #[allow(warnings)]
    #[doc(hidden)]
    pub mod trace_capnp {
        include!(concat!(
            env!("OUT_DIR"),
            "/opentelemetry/capnp/trace/v1/trace_capnp.rs"
        ));
    }

    // this mod contains file generated by capnp or other build tools.
    // we shouldn't manually change it. Thus skip format and lint check.
    #[rustfmt::skip]
    #[allow(warnings)]
    #[doc(hidden)]
    pub mod common_capnp {
        include!(concat!(
            env!("OUT_DIR"),
            "/opentelemetry/capnp/common/v1/common_capnp.rs"
        ));
    }

    // this mod contains file generated by capnp or other build tools.
    // we shouldn't manually change it. Thus skip format and lint check.
    #[rustfmt::skip]
    #[allow(warnings)]
    #[doc(hidden)]
    pub mod resource_capnp {
        include!(concat!(
            env!("OUT_DIR"),
            "/opentelemetry/capnp/resource/v1/resource_capnp.rs"
        ));
    }

    // this mod contains file generated by capnp or other build tools.
    // we shouldn't manually change it. Thus skip format and lint check.
    #[rustfmt::skip]
    #[allow(warnings)]
    #[doc(hidden)]
    pub mod trace_service_capnp {
        include!(concat!(
            env!("OUT_DIR"),
            "/opentelemetry/capnp/collector/trace/v1/trace_service_capnp.rs"
        ));
    }
    pub use common_capnp::*;
    pub use resource_capnp::*;
    pub use trace_capnp::*;
    pub use trace_service_capnp::*;

    // pub use crate::transform::common::capnp::Attributes;
}
