#![cfg_attr(docsrs, feature(doc_auto_cfg))]
//! This crate contains generated files from [opentelemetry-capnp]() crate in this workspace.
//! repository and transformation between types from generated files and types defined in [schema]() directory of this workspace.

// this mod contains file generated by capnp or other build tools.
// we shouldn't manually change it. Thus skip format and lint check.
#[rustfmt::skip]
#[allow(warnings)]
#[doc(hidden)]
pub mod capnp;

// pub use crate::capnp::capnp_rpc;

pub use crate::capnp::capnp_rpc;
#[doc(hidden)]
pub use crate::capnp::capnp_rpc::{common_capnp, resource_capnp, trace_capnp, trace_service_capnp};
pub mod transform;
