#![cfg_attr(docsrs, feature(doc_auto_cfg))]
//! This crate contains generated files from [opentelemetry-capnp]() crate in this workspace.
//! repository and transformation between types from generated files and types defined in [schema]() directory of this workspace.
//!

// proto mod contains file generated by protobuf or other build tools.
// we shouldn't manually change it. Thus skip format and lint check.
#[rustfmt::skip]
#[allow(warnings)]
#[doc(hidden)]
mod capnp;

// #[cfg(feature = "gen-tonic-messages")]
// pub use proto::tonic;

pub mod transform;
