#![cfg_attr(docsrs, feature(doc_auto_cfg))]
//! This crate contains generated files from [opentelemetry-capnp]() crate in this workspace.
//! repository and transformation between types from generated files and types defined in [schema]() directory of this workspace.

pub mod transform;

// this mod contains file generated by capnp or other build tools.
// we shouldn't manually change it. Thus skip format and lint check.
#[rustfmt::skip]
#[allow(warnings)]
#[doc(hidden)]
pub mod trace_capnp {
    include!(concat!(
        env!("OUT_DIR"),
        "/opentelemetry/capnp/trace/v1/trace_capnp.rs"
    ));
}

// this mod contains file generated by capnp or other build tools.
// we shouldn't manually change it. Thus skip format and lint check.
#[rustfmt::skip]
#[allow(warnings)]
#[doc(hidden)]
pub mod common_capnp {
    include!(concat!(
        env!("OUT_DIR"),
        "/opentelemetry/capnp/common/v1/common_capnp.rs"
    ));
}

// this mod contains file generated by capnp or other build tools.
// we shouldn't manually change it. Thus skip format and lint check.
#[rustfmt::skip]
#[allow(warnings)]
#[doc(hidden)]
pub mod resource_capnp {
    include!(concat!(
        env!("OUT_DIR"),
        "/opentelemetry/capnp/resource/v1/resource_capnp.rs"
    ));
}
pub use common_capnp::*;
pub use resource_capnp::*;
pub use trace_capnp::*;
